global: 
  scrape_interval: 1m

scrape_configs: 
  - job_name: "prometheus" 
    scrape_interval: 1m 
    static_configs: 
    - targets: ["localhost:9090"]

  - job_name: "node" 
    static_configs: 
    - targets: ["node-exporter:9100"]

  - job_name: "zabbix-server" 
    scrape_interval: 2s 
    static_configs: 
    - targets: ["10.20.1.40:8081"]  
  
  - job_name: "cadvisor" 
    scrape_interval: 2s 
    static_configs: 
    - targets: ["10.20.1.37:9100"]
  #- job_name: "hvhost01" 
   # scrape_interval: 5s 
    #static_configs: 
    #- targets: ["10.20.1.40:9182"]